General: 
  Username: <testing@gmail.com>
  Password: 123
  MailServer: 127.0.0.1
  SMTP: 2225
  POP3: 3335
  Autoload: 10

Filter:
  - From:
    - phuong@dz.com
    - testing@gmail.com
    To: Project

  - Subject: 
    - "urgent"
    - "ASAP"
    To: Important 

  - Content:
    - "report"
    - "meeting"
    To: Work

  - Spam:
    - "virus"
    - "hack"
    - "crack"
    To: Spam